name: destroy-all-the-things

trigger: none

variables:
  - group: aws-keys
  - name: AWS_REGION
    value: AATT_AWS_REGION # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: AATT_APP_NAME # This value was modified by the initial-setup python script

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created

jobs:
- job: DeleteK8SResources
  displayName: 'Delete Kubernetes Resources'
  steps:

  - task: HelmInstaller@0
    inputs:
      displayName: Install helm
      helmVersion: '3.11.2'
      installKubectl: true

  - task: AWSCLI@1
    displayName: 'Update KubeConfig'
    inputs:
      awsCredentials: 'aws'
      regionName: '$(AWS_REGION)' 
      awsCommand: 'eks'
      awsSubCommand: 'update-kubeconfig'
      awsArguments: '--name $(APP_NAME)-cluster --region $(AWS_REGION)' 

  - script: | 
      mkdir ~/.aws
      echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
      echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
    displayName: 'Configure AWS Profile'

  # Before deleting all Ingresses we eliminate ArgoCD because if we don't, it will re-deploy the Ingresses, automatically creating untracked AWS Application Load Balancers, which would mess with the terraform destroy  
  # We also need to remove the finalizers from the Kiali CR for deletion to be successful, it's a known issue (https://kiali.io/docs/installation/installation-guide/install-with-helm/#known-problem-uninstall-hangs-unable-to-delete-the-kiali-cr)
  - script: | 
      kubectl delete -n argocd applications.argoproj.io argocd-apps
      kubectl patch kiali kiali -n service-mesh -p '{"metadata":{"finalizers": []}}' --type=merge
      kubectl delete -n argocd applications.argoproj.io --all
      helm uninstall -n argocd argocd
    displayName: 'Delete Applications & ArgoCD'

  # Before deleting all infra we make sure there are no existing ingresses so the terraform destroy isn't messed up by the existance of untracked AWS Application Load Balancers
  - script: | 
        kubectl delete ingress --all --all-namespaces
    displayName: 'Delete Ingresses'

  # We also delete all EBS volumes created through Persistent Volumes
  - script: | 
        kubectl delete persistentvolumeclaims --all --all-namespaces
        kubectl delete persistentvolumes --all --all-namespaces
    displayName: 'Delete Persisten Volumnes'


- job: DeleteAWSInfrastructure
  displayName: 'Delete AWS Infrastructure'
  dependsOn: DeleteK8SResources
  steps:
  - task: TerraformInstaller@0
    displayName: Install terraform
    inputs:
      terraformVersion: '1.4.6'

  - task: TerraformCLI@1
    displayName: 'Terraform Init'
    inputs:
      command: init
      workingDirectory: 'terraform/aws'
      backendType: aws
      backendServiceAws: aws
      providerServiceAws: 'aws'
      providerAwsRegion: $(AWS_REGION)

  - task: TerraformCLI@1
    displayName: 'Terraform Destroy AWS Infra'
    inputs:
      command: destroy
      workingDirectory: 'terraform/aws'
      providerServiceAws: 'aws'
      providerAwsRegion: $(AWS_REGION) 
    continueOnError: true
